version: "3"

services:
  app:
    container_name: salon-user-app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    restart: always
    ports:
      - ${APP_FORWARD_PORT:-3000}:${PORT:-3000}
    expose:
      - ${PORT:-3000}
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    networks:
      - salon_management_shared_network

networks:
  salon_management_shared_network:
    name: salon_management_shared_network
    external: true

#docker network create salon_management_shared_network
